[package]
name = "mpicd-benchmarks"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.152", features = ["derive"] }
clap = { version = "4.1.4", features = ["derive"] }
mpi = "0.6.0"
serde_yaml = "0.9"
