[workspace]
resolver = "2"
members = [
    "mpicd",
    "mpicd-capi",
    "mpicd-ucx-sys",
    "mpicd-pmix-sys",
    "mpicd-rust-benchmarks",
]

[profile.release]
# Keep debug symbols for the release build
strip = "debuginfo"
