[package]
name = "mpicd"
version = "0.1.0"
edition = "2021"

[dependencies]
mpicd-ucx-sys = { path = "../mpicd-ucx-sys" }
mpicd-pmix-sys = { path = "../mpicd-pmix-sys" }
nix = "0.26.2"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
log = "0.4.21"
