benchmarks:
  latency:
    ./params/latency/simple.yaml:
      #message-pack
      #postcard,
      - flat
      - bincode
      - iovec
      - rsmpi
    ./params/latency/complex-noncompound.yaml:
      #message-pack
      #postcard
      - flat
      - bincode
      - iovec
      - rsmpi
    ./params/latency/complex-compound.yaml:
      #message-pack
      #postcard
      - bincode
      - iovec
      # rsmpi does not support complex-compound datatypes
  bw:
    ./params/bw/complex-noncompound.yaml:
      - iovec
      - bincode
      - flat
      - rsmpi
    ./params/bw/complex-compound.yaml:
      - iovec
      - bincode
scripts:
  latency:
    # message-pack
    flat:
      script: './scripts/latency_flat.sh'
      env: {}
    bincode:
      script: './scripts/latency_bincode.sh'
      env: {}
    iovec:
      script: './scripts/latency_iovec.sh'
      env: {}
    rsmpi:
      script: './scripts/latency_rsmpi.sh'
      env:
        OMPI_MCA_pml: ucx
  bw:
    bincode:
      script: './scripts/bw_bincode.sh'
      env: {}
    iovec:
      script: './scripts/bw_iovec.sh'
      env: {}
    rsmpi:
      script: './scripts/bw_rsmpi.sh'
      env:
        OMPI_MCA_pml: ucx
    flat:
      script: './scripts/bw_flat.sh'
      env: {}
