[package]
name = "datatypes"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.152", features = ["derive"] }
mpi = { version = "0.6.0", features = ["derive"] }
iovec = { path = "../iovec" }
flat = { path = "../flat" }
flat-derive = { path = "../flat-derive" }
