[package]
name = "mpicd-capi"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
mpicd = { path = "../mpicd" }
lazy_static = "1.4.0"
log = "0.4.21"
env_logger = "0.11.3"

[profile.release]
# Keep debug symbols for the release build
strip = "debuginfo"
